### ISSUE TITLE
🐛bug: plugin doesn't respect `config.source.define` rewrites

### ISSUE THREAD

**Issue by vegerot** [rspack-contrib/rsbuild-plugin-type-check#12]
I reproduced the bug in https://github.com/vegerot/rsbuild-plugin-type-check/commit/repro-define-bug .  Check there for precise reproduction

Reproduction steps (high level):
1. In rsbuild.config.ts, add `source.define` section with a rewrite
2. Use the rewrite in your code
3. Run type checker

Expected: it works
Actual: it no worky

# Reproduction steps:
1. add `vegerot/rsbuild-plugin-type-check` remote
2. switch to `repro-define-bug` branch https://github.com/vegerot/rsbuild-plugin-type-check/commit/repro-define-bug
3. run `pnpm test`

Expected: Tests should pass
Actual: Test fails

**Comment by chenjiahan** [comment]
Hi, `source.define` is a compile-time feature, it cannot affect the type checking result, because it is TypeScript (tsc) that performs the type checking.
